### ISSUE TITLE
Catppuccin Latte (light theme) on YouTube broke the contrast on subscribe and other buttons.

### ISSUE THREAD

**Issue by yaycupcake** [catppuccin/youtube#20]
My YouTube setting is on light theme. I have been using Catppuccin Latte for months with no issue, but today the style got updated, and seems to have broken the contrast on buttons below the video player, including the subscribe button.

YouTube with no extra CSS, for comparison:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/11069809/203498161-77d2664f-076a-4f0b-9ad0-b74999e37cc7.png">

YouTube with Catppuccin Latte:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/11069809/203498230-a1ce721e-8c4d-490e-86fa-b3a6ffa9a848.png">

YouTube with a band-aid code fix that I wrote, that is what I would expect it to look like:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/11069809/203498366-1a13814a-e270-4298-a290-807a43058d2a.png">

The code I used in an extra style to band-aid patch the issue:
```css
.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--filled,
.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--tonal,
tp-yt-paper-button.ytd-subscribe-button-renderer {
    color: var(--yt-spec-text-primary)!important;
}
```

I'm unsure which color(s) would be ideal for usage out of the Catppuccin palette, or if this is pulling the correct color with that variable (I haven't had a moment to dig into the code myself to see what's what) but hopefully the selectors (which I just pulled out of the inspector) should help make it easy to fix. I think it's actually just the second one that matters in this case -- again, I just did a quick band-aid fix and grabbed the entire selector from the inspector.

Let me know if any further context is needed, I'd be happy to provide any information I can. Thanks.
