### ISSUE TITLE
Description text being styled like links.

### ISSUE THREAD

**Issue by kenxjy** [catppuccin/youtube#61]
Example:  
![image](https://github.com/catppuccin/youtube/assets/43609718/d7b7845a-167b-47df-ac3c-063a7407623e)

Example when `:hover` is active.
![image](https://github.com/catppuccin/youtube/assets/43609718/323d5fd8-7406-4f04-8648-10750c9f00d7)

It looks like Youtube is overwriting a lot of elements with the class `.yt-core-attributed-string--link-inherit-color` with an inline style that changes the color. 

This is what I saw in the element inspector:  
![image](https://github.com/catppuccin/youtube/assets/43609718/1e193995-efa3-4f7e-b85d-8fc6d3fd88d8)

I made the following changes at line 615. Seems to work for now.
```less
    .yt-core-attributed-string--link-inherit-color {
      color: @text !important;
      /*
      &:hover {
        color: @teal !important;
      }
      */
    }
```

This was tested on Firefox and Edge with no extensions except Stylus (and no other themes) installed.
